### ISSUE TITLE
Error when parse docker json log timestamp

### ISSUE THREAD

**Issue by joeyux** [jzwlqx/fluent-pilot#1]
I use out_file plugin to write logfile, and all generated filename like xxx.19700101_1.xxx. It look likes error when parse timestamp from docker json log, fix it with add `time_format %Y-%m-%dT%H:%M:%S` to fluentd.tpl source section.

**Comment by jzwlqx** [comment]
Sorry, i don't understand what your mean. Could you describe the problem with more context, such as your log format, labels on docker containers. It will be helpful if you provide some error log.

**Comment by joeyux** [comment]
Here is my modified fluentd.tpl, for collect docker log and save to filesystem.
```
{{range .configList}}
<source>
  @type tail
  tag {{ $.containerId }}.{{ .Name }}
  path {{ .HostDir }}/{{ .File }}
  format {{ .Format }}
  pos_file /pilot/pos/fluentd.pos
  refresh_interval 5
</source>

<filter {{ $.containerId }}.{{ .Name }}>
@type add_time
time_key @timestamp
</filter>

<filter {{ $.containerId }}.{{ .Name }}>
@type record_transformer
<record>
host "#{Socket.gethostname}"
{{range $key, $value := .Tags}}
{{ $key }} {{ $value }}
{{end}}

{{if not .Tags.target}}target {{if $.source.Application}}{{ $.source.Application }}-{{end}}{{ .Name }}{{end}}

{{if $.source.Application}}docker_app {{ $.source.Application }} {{end}}
{{if $.source.Service}}docker_service {{ $.source.Service }} {{end}}
{{if $.source.Container}}docker_container {{ $.source.Container }} {{end}}
</record>
</filter>

<match {{ $.containerId }}.{{ .Name }}>
@type file
path /pilot/logs/{{ $.source.Application }}/{{ $.source.Container }}
flush_interval 1h
format single_value
message_key log
add_newline false
</match>

{{end}}
```

The generated filename likes `testlog_testlog_1.19700101.b549caa428d1e813b`, then I add `time_format` into source section, the generated filename now with correct date likes `testlog_testlog_1.20170303.b549cabf95bdc23bb`.

```
{{range .configList}}
<source>
  @type tail
  tag {{ $.containerId }}.{{ .Name }}
  path {{ .HostDir }}/{{ .File }}
  format {{ .Format }}
  time_format %Y-%m-%dT%H:%M:%S
  pos_file /pilot/pos/fluentd.pos
  refresh_interval 5
</source>
...
```

**Comment by jzwlqx** [comment]
It now add a time_format field when work with docker stdout. 
Thanks for the issue.
