### ISSUE TITLE
support devicemapper storage?

### ISSUE THREAD

**Issue by yiqinguo** [jzwlqx/fluent-pilot#3]
Which support file storage? support devicemapper?
How it is collected the log file in container ?

**Comment by yiqinguo** [comment]
就是说容器的日志文件采集的话也要挂载出来吗

**Comment by BSWANG** [comment]
@yiqinguo 如果使用阿里云容器服务，会默认对这个label处理，并自动挂载，如果不在容器服务，需要通过volume挂载。

**Comment by yiqinguo** [comment]
哦哦 那就是说其实这个容器内文件采集的话其实是依赖阿里云的

**Comment by BSWANG** [comment]
@yiqinguo 不依赖阿里云容器服务。你可以理解是阿里云容器服务专门为fluent-pilot做了优化。
不在阿里云的容器服务上的话，只要手动声明日志的目录作为volume就好，比如：
```
docker run \
  -v /var/log \   #声明volume，挂载也可以，比如-v /path/on/host:/var/log
  --label aliyun.logs.nginx=/var/log/access.log \
  nginx:latest
```

**Comment by yiqinguo** [comment]
方便加个微信聊一下吗  我对这个项目非常感兴趣

**Comment by yiqinguo** [comment]
方便加个微信聊一下吗 我对这个项目非常感兴趣 gyq19910606

**Comment by BSWANG** [comment]
@yiqinguo 已加，没有问题的话我先关闭这个issue啦~
