### ISSUE TITLE
filebeat 收集日志出现大量文件句柄未释放的问题

### ISSUE THREAD

**Issue by oldthreefeng** [jzwlqx/fluent-pilot#321]
@oscarlear  如果需要添加filebeat一些参数, 是不是修改 `/pilot/config.tpl` 配置文件? 

ref:
https://cloud.tencent.com/developer/article/1389092
https://developer.aliyun.com/article/637173
https://github.com/elastic/beats/issues/2608
https://www.cnblogs.com/JetpropelledSnake/p/13528800.html

比如
```
close_older: 10m      #释放速度加快6倍, default is 1h. 
force_close_files: true
```

**Comment by oscarlear** [comment]
我看了下，如果是修改你上面的两个参数，直接修改log-pilot/assets/filebeat/filebeat.tpl（源码目录）这个文件，其他的参数的话，需要看是哪些配置，基本上是修改log-pilot/assets/filebeat/目录下的两个文件

**Comment by oldthreefeng** [comment]
感谢您的回复.  

我这边直接使用cm 挂载 `filebeat.tpl `文件. 是不需要改镜像逻辑的, 对么?

**Comment by oscarlear** [comment]
应该是可以的，镜像逻辑应该是不用修改，你可以试一下，我每次修改模板之后都会重新打包镜像，没有用cm挂载

**Comment by oldthreefeng** [comment]
我这边试试先. 这个问题困扰了我很久.  其他没什么问题了. 我issue关闭了.
