### ISSUE TITLE
是否支持containerd

### ISSUE THREAD

**Issue by Phoebus888** [jzwlqx/fluent-pilot#336]
是否支持containerd

**Comment by Colstuwjx** [comment]
Duplicate of #241

**Comment by xjdszp** [comment]
遇到相同问题，看了源码只支持docker引擎

**Comment by zhajingwen** [comment]
不支持，但是这里有个改进版：https://github.com/AliyunContainerService/log-pilot/issues/349
但是我没弄懂回答中的https://github.com/AliyunContainerService/log-pilot/issues/349#issuecomment-1461623117
能解释下吗？
